### ISSUE TITLE
missing rf_model

### ISSUE THREAD

**Issue by codebit23** [Gardner-BinfLab/TIsigner_paper_2019#1]
Hello, 
I looked at the code in optimization.py, it seems missing rf_model.
self.rf_model = self.validate_model(rf_model).
look like you pre-trained features, 
could you share the code for training? 
thanks

**Comment by lcscs12345** [comment]
Hi @codebit23 ,

Thank you for your interest. The model has to be exported from the gini_features.ipynb after training the random forest. The optimiser.py uses that model to evaluate cost function using different sequence features for the sequence optimisation.
But eventually we just used one feature "accessibility" so that optimiser.py is no longer needed. The other script opt.py optimises sequence based on one feature only and doesn't require random forest model.

Cheers,
Lim and Bikash

**Comment by codebit23** [comment]
Thanks for your input. That helps.
